#!/bin/bash
# usage: ./version.sh [major-version]

MAJOR="${1}"

# Only works when tree is fully committed.
test -z "$(git status -s)"
if [[ ${?} -ne 0 ]]; then
    echo "commit work first"
    exit 1
fi

LAST_TAG="$(git tag -l --sort=committerdate 'v*'|tail -1)"
if [[ -z "${LAST_TAG}" ]]; then
    echo "no base tag to work with, using v0.0.0"
    LAST_TAG="v0.0.0"
fi

BITS=(${LAST_TAG//./ })
if [[ -n "${MAJOR}" ]]; then
    MINOR="0"
else
    MAJOR="${BITS[1]}"
    MINOR=$((${BITS[2]}+1))
fi
NEW_TAG="${BITS[0]}.${MAJOR}.${MINOR}"

cat > version.go <<EOF
// Autogenerated by ${0}

package benwh

const userAgent = "BenWH_Go_Client/${NEW_TAG}"
EOF

git add version.go
git commit -s -m "Update package release to ${NEW_TAG}"
git tag "${NEW_TAG}"
